MTL       = ../mtl
CHDRS     = $(wildcard *.h) $(wildcard $(MTL)/*.h)
EXEC      = minisat
CFLAGS    = -fno-exceptions -I$(MTL) -Wall -ffloat-store $(EXTRACFLAGS)
LFLAGS    = -lz

include ../mtl/template.mk
